hint_files:
  - "https://github.com/gordonwatts/hep-programming-hints/raw/refs/heads/main/servicex-hints.md"
  - "https://raw.githubusercontent.com/gordonwatts/hep-programming-hints/refs/heads/main/xaod-hints.md"
  - "https://github.com/gordonwatts/hep-programming-hints/raw/refs/heads/main/awkward-hints.md"
  - "https://github.com/gordonwatts/hep-programming-hints/raw/refs/heads/main/vector-hints.md"
  - "https://github.com/gordonwatts/hep-programming-hints/raw/refs/heads/main/hist-hints.md"
prompt: "You are an expert HEP programmer. Use the provided hints to answer questions and generate code."
